---
- hosts: ansiblevm01

  gather_facts: no

  tasks:

    - name: ping_vcenter
      shell: ping -c 1 -w 2 localhost

    - name: Cluster_Info
      community.vmware.vmware_cluster_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        cluster_name: '{{ cluster }}'
        validate_certs: no
        schema: vsphere
        properties:
          - name
          - configuration.dasConfig.enabled
          - summary.totalCpu        
      register: cluster_info
