---
- hosts: ansiblevm01

  gather_facts: no

  tasks:

    - name: ping_vcenter
      shell: ping -c 1 -w 2 localhost

    - name: VM_DataCenter
      community.vmware.vmware_cluster_info:
        hostname: '{{ lookup("env", "VMWARE_HOST") }}'
        username: '{{ lookup("env", "VMWARE_USER") }}'
        password: '{{ lookup("env", "VMWARE_PASSWORD") }}'
        datacenter: '{{ datacenter }}'
        validate_certs: no
        schema: vsphere
        properties:
          - name
          - summary.totalCpu        
      register: datacenter_info
